export const batches = [
  'BTech First Year',
  'BTech Second Year',
  'BTech Third Year',
  'BTech Fourth Year',
  'BArch First Year',
  'BArch Second Year',
  'BArch Third Year',
  'BArch Fourth Year',
  'BArch Fifth Year',
  'MTech First Year',
  'MTech Second Year',
  'MArch First Year',
  'MArch Second Year',
  'MSc First Year',
  'MSc Second Year',
  'MCA First Year',
  'MCA Second Year',
  'MCA Third Year',
  'PhD',
  'MBA First Year',
  'MBA Second Year',
  'MA First Year',
  'MA Second Year',
  'Faculty'
];
